version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
    network_mode: "host"
    env_file:
      - env/dev/.env.postgres
      - env/dev/.env.backend
