# Generated by Django 3.2.3 on 2021-05-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OP', 'OPEN'), ('SEMI', 'CAUTION'), ('CLOSED', 'CLOSED')], default='CLOSED', max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Border Statuses',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='OriginCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations', models.ManyToManyField(related_name='destinations', through='countries.BorderStatus', to='countries.Country')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='countries.country')),
            ],
            options={
                'verbose_name_plural': 'Origin Countries',
            },
        ),
        migrations.AddField(
            model_name='borderstatus',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
        migrations.AddField(
            model_name='borderstatus',
            name='origin_country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='countries.origincountry'),
        ),
        migrations.AlterUniqueTogether(
            name='borderstatus',
            unique_together={('destination', 'origin_country')},
        ),
    ]
